[FIX] cetmix_tower_server: Reference generation
This commit fixes the following issue:

Steps to reproduce
------------------

- Create a new flight plan with an empty reference​ field
- Click "Save"

Expected result
---------------

- Flight plan is created
- Reference is generated automatically

Current result
--------------

Error: 'bool' object has no attribute 'strip'.

Why?
----

Because Odoo adds empty field value to vals as 'False'.

Task: 4058